#idk what is that
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: first
#          predicates:
#            - Path=/first/
#          uri: localhost:8001
#
#        - id: second
#          predicates:
#            - Path=/second/
#          uri: localhost:8002
