spring:
  application:
    name: API-GATEWAY
  server:
    port: 8080
  cloud:
    gateway:
      routes:
        - id: library-service
          uri: http://localhost:8001
          predicates:
            - Path=/library/**

        - id: test-service
          uri: http://localhost:8002
          predicates:
            - Path=/test/**

